# Generated by Django 4.2.8 on 2023-12-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(default='unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 9:30', '8:00 - 9:30'), ('9:45 - 11:15', '9:45 - 11:15'), ('11:30 - 13:00', '11:30 - 13:00'), ('13:30 - 15:00', '13:30 - 15:00'), ('15:15 - 16:45', '15:15 - 16:45'), ('17:00 - 18:30', '17:00 - 18:30'), ('18:45 - 20:15', '18:45 - 20:15')], default='8:00 - 9:30', max_length=50),
        ),
    ]
